package libraryManagement;

import javax.swing.JOptionPane;
import java.awt.Frame;
import javax.swing.JDialog;

/**
 *
 * @author Nicholas Raines and Voluntas Kini
 */
public class AddBookDialog extends javax.swing.JDialog{

    private Library library;

  // Constructor for this dialog; assigns a parent window, enforces modal behavior (requires user interaction before returning to main window), and provides access to the Library object for ArrayList operations.
    public AddBookDialog(java.awt.Frame parent, boolean modal, Library library) {
        super(parent, modal);
        this.library = library;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        addBookDialogTitle = new javax.swing.JLabel();
        titleBookTitle = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        isbnTitle = new javax.swing.JLabel();
        isbnField = new javax.swing.JTextField();
        authorTitle = new javax.swing.JLabel();
        authorField = new javax.swing.JTextField();
        addBookButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addBookDialogTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        addBookDialogTitle.setText("Add A Book");

        titleBookTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titleBookTitle.setText("Title");

        isbnTitle.setText("ISBN");

        authorTitle.setText("Author");

        addBookButton.setText("Add");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(authorTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(isbnTitle)
                        .addGap(18, 18, 18)
                        .addComponent(isbnField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleBookTitle)
                        .addGap(18, 18, 18)
                        .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addBookDialogTitle)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addBookButton)
                        .addGap(172, 172, 172))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addBookDialogTitle)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleBookTitle)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnTitle)
                    .addComponent(isbnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorTitle)
                    .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addBookButton)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String title = titleField.getText();
        String isbn = isbnField.getText();
        String authorName = authorField.getText();

        if (!title.isBlank() && !isbn.isBlank() && !authorName.isBlank()) {
            Author author = new Author(authorName);
            Book book = new Book(title, isbn, author);

            library.addBook(book);

            JOptionPane.showMessageDialog(this, "Book added successfully!");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "All fields must be filled.");
        }
        addBookButton.setSelected(false);
    }                                             


    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton addBookButton;
    private javax.swing.JLabel addBookDialogTitle;
    private javax.swing.JTextField authorField;
    private javax.swing.JLabel authorTitle;
    private javax.swing.JTextField isbnField;
    private javax.swing.JLabel isbnTitle;
    private javax.swing.JLabel titleBookTitle;
    private javax.swing.JTextField titleField;
    // End of variables declaration                   
}

