package libraryManagement;

import javax.swing.JOptionPane;

/**
 *
 * @author Nicholas Raines
 */

public class AddCardholderDialog extends javax.swing.JDialog {
    private Library library;

    // Constructor that ues 
    public AddCardholderDialog(java.awt.Frame parent, boolean modal, Library library) {
        super(parent, modal);
        this.library = library;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        addMemberTitle = new javax.swing.JLabel();
        nameTitle = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        memberIdTitle = new javax.swing.JLabel();
        memberIdField = new javax.swing.JTextField();
        addMemberButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addMemberTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addMemberTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addMemberTitle.setText("Add A Member");
        addMemberTitle.setAlignmentY(0.0F);

        nameTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTitle.setText("Name");

        memberIdTitle.setText("Member ID");

        addMemberButton.setText("Add Member");
        addMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(memberIdTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(memberIdField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameTitle)
                        .addGap(35, 35, 35)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addMemberTitle)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addMemberButton)
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addMemberTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTitle)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberIdTitle)
                    .addComponent(memberIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(addMemberButton)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void addMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        String name = nameField.getText();
        String id = memberIdField.getText();
    
        if (!name.isBlank() && !id.isBlank()) {
            if (library.findCardholderByID(id) == null) {
                Cardholder cardholder = new Cardholder(id, name);
                library.addCardholder(cardholder);
                JOptionPane.showMessageDialog(this, "Member added: " + name);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Member ID already exists.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "All fields are required.");
        }
        addMemberButton.setSelected(false);
    }                                               


    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton addMemberButton;
    private javax.swing.JLabel addMemberTitle;
    private javax.swing.JTextField memberIdField;
    private javax.swing.JLabel memberIdTitle;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameTitle;
    // End of variables declaration                   
}

