/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libraryManagement;

import javax.swing.JOptionPane;
import java.time.LocalDate;

/**
 *
 * @author Nicholas Raines
 */
public class CheckoutBookDialog extends javax.swing.JDialog {
    
    private Library library;
    
    /**
     * Creates new form CheckoutBookDialog
     */
    public CheckoutBookDialog(java.awt.Frame parent, boolean modal, Library library) {
        super(parent, modal);
        this.library = library;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        checkoutBooksTitle = new javax.swing.JLabel();
        checkoutMemberIDTitle = new javax.swing.JLabel();
        checkoutMemberIDField = new javax.swing.JTextField();
        titleCheckoutTitle = new javax.swing.JLabel();
        bookTitleField = new javax.swing.JTextField();
        checkoutButtonTitle = new javax.swing.JLabel();
        checkoutButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        checkoutBooksTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkoutBooksTitle.setText("Checkout Books");

        checkoutMemberIDTitle.setText("Member ID");

        titleCheckoutTitle.setText("Title of the Book");

        checkoutButtonTitle.setText("Checkout");

        checkoutButton.setActionCommand("");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkoutBooksTitle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(checkoutMemberIDTitle)
                                .addComponent(checkoutMemberIDField)
                                .addComponent(titleCheckoutTitle)
                                .addComponent(bookTitleField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkoutButton)
                                .addGap(64, 64, 64))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(checkoutButtonTitle)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkoutBooksTitle)
                .addGap(22, 22, 22)
                .addComponent(checkoutMemberIDTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkoutMemberIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titleCheckoutTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkoutButtonTitle)
                .addGap(2, 2, 2)
                .addComponent(checkoutButton)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String memberID = checkoutMemberIDField.getText();
        String bookTitle = bookTitleField.getText();
        
        Book book = null;
        for(Book b : library.getBooks()) {
            if(b.getTitle().equalsIgnoreCase(bookTitle)) {
                book = b;
                break;
            }
        }
        
        Cardholder cardholder = library.findCardholderByID(memberID);
        
        if(book == null) {
            JOptionPane.showMessageDialog(this, "Book not found.");
        } else if (cardholder == null) {
            JOptionPane.showMessageDialog(this, "Cardholder not found.");
        } else if (book.isBorrowed()) {
            JOptionPane.showMessageDialog(this, "That book is already checked out.");
        } else {
            Rental rental = new Rental(book, cardholder);
            rental.setCheckoutDate(LocalDate.now());
            rental.setDueDate(LocalDate.now().plusDays(31));
            library.addRental(rental);
            book.setBorrowed(true);
            book.setRental(rental);
            JOptionPane.showMessageDialog(this, "The book was checked out. Happy reading " + cardholder.getName() + "! The book is due in 31 days. Late fees may be accrued thereafter.");
        }
        // Used to make the radio button not have a blue circle like it's selected after finished entering user info
        checkoutButton.setSelected(false);
    }                                              


    // Variables declaration - do not modify                     
    private javax.swing.JTextField bookTitleField;
    private javax.swing.JLabel checkoutBooksTitle;
    private javax.swing.JRadioButton checkoutButton;
    private javax.swing.JLabel checkoutButtonTitle;
    private javax.swing.JTextField checkoutMemberIDField;
    private javax.swing.JLabel checkoutMemberIDTitle;
    private javax.swing.JLabel titleCheckoutTitle;
    // End of variables declaration                   
}

