/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libraryManagement;

import javax.swing.JOptionPane;

/**
 *
 * @author Nicholas Raines and Brett Swardenski
 */
public class ReturnBookDialog extends javax.swing.JDialog {
    
    private Library library;

    /**
     * Creates new form ReturnBookDialog
     */
    public ReturnBookDialog(java.awt.Frame parent, boolean modal, Library library) {
        super(parent, modal);
        this.library = library;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        bookReturnTitle = new javax.swing.JLabel();
        memberIDTitle = new javax.swing.JLabel();
        memberIDField = new javax.swing.JTextField();
        returnedBookTitle = new javax.swing.JLabel();
        returnedBookField = new javax.swing.JTextField();
        returnBookButtonTitle = new javax.swing.JLabel();
        returnBookButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bookReturnTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bookReturnTitle.setText("Book Return");

        memberIDTitle.setText("Member ID");

        returnedBookTitle.setText("Title of the Book");

        returnBookButtonTitle.setText("Return Book");

        returnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(149, Short.MAX_VALUE)
                        .addComponent(bookReturnTitle)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberIDField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(returnedBookTitle)
                                    .addComponent(memberIDTitle))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(returnedBookField))))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(returnBookButtonTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(returnBookButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookReturnTitle)
                .addGap(18, 18, 18)
                .addComponent(memberIDTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnedBookTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnedBookField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnBookButtonTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returnBookButton)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        String memberID = memberIDField.getText().trim();
        String bookTitle = returnedBookField.getText().trim();
        
        if(memberID.isEmpty() || bookTitle.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both a member ID and a book title.");
            return;
        }
        
        Cardholder cardholder = library.findCardholderByID(memberID);
       
        Book targetBook = null;
        for(Book b: library.getBooks()) {
            if(b.getTitle().equalsIgnoreCase(bookTitle)) {
                targetBook = b;
                break;
            }
        }
        
        if(cardholder == null) {
            JOptionPane.showMessageDialog(this, "There is no member with that ID.");
        }
        
        if(targetBook == null) {
            JOptionPane.showMessageDialog(this, "We don't have a book listed by that name.");
        }
        
        library.returnBook(targetBook, cardholder);
        double fee = targetBook.getRental() != null ? targetBook.getRental().getLateFee() : 0.0;
        String message = "The book was returned.";
        if(fee > 0) {
            message += String.format("There was a late fee assessed. You owe: $%.2f", fee);
        }
        
        JOptionPane.showMessageDialog(this, message);
        
        memberIDField.setText("");
        returnedBookField.setText("");
        // Used to make the radio button not have a blue circle like it's selected after finished entering user info
        returnBookButton.setSelected(false);
    }                                                


    // Variables declaration - do not modify                     
    private javax.swing.JLabel bookReturnTitle;
    private javax.swing.JTextField memberIDField;
    private javax.swing.JLabel memberIDTitle;
    private javax.swing.JRadioButton returnBookButton;
    private javax.swing.JLabel returnBookButtonTitle;
    private javax.swing.JTextField returnedBookField;
    private javax.swing.JLabel returnedBookTitle;
    // End of variables declaration                   
}

