package libraryManagement;

import javax.swing.JOptionPane;
import javax.swing.JDialog;

/**
 *
 * @author Nicholas Raines
 */
public class SearchCardholderDialog extends javax.swing.JDialog {

    private Library library;

    /**
     * Creates new form SearchCardholderDialog
     */
    public SearchCardholderDialog(java.awt.Frame parent, boolean modal, Library library) {
        super(parent, modal);
        this.library = library;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        memberSearchTitle = new javax.swing.JLabel();
        memberIdTitle = new javax.swing.JLabel();
        memberIdField = new javax.swing.JTextField();
        searchButton = new javax.swing.JRadioButton();
        memberTextScrollPane = new javax.swing.JScrollPane();
        memberTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        memberSearchTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        memberSearchTitle.setText("Member Search");
        memberSearchTitle.setToolTipText("");

        memberIdTitle.setText("MemberID");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        memberTextArea.setColumns(20);
        memberTextArea.setRows(5);
        memberTextArea.setEnabled(false);
        memberTextScrollPane.setViewportView(memberTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(memberTextScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(memberIdTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberSearchTitle)
                            .addComponent(memberIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(memberSearchTitle)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberIdTitle)
                    .addComponent(memberIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(memberTextScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String id = memberIdField.getText();

        if (!id.isBlank()) {
            Cardholder c = library.findCardholderByID(id);
            if (c != null) {
                memberTextArea.setText("Name: " + c.getName() + "\nID: " + c.getMemberID());
            } else {
                memberTextArea.setText("No member found with ID: " + id);
            }
        } else {
            memberTextArea.setText("Please enter a Member ID.");
        }
        // Used to make the radio button not have a blue circle like it's selected after finished entering user info
        searchButton.setSelected(false);
    }                                            


    // Variables declaration - do not modify                     
    private javax.swing.JTextField memberIdField;
    private javax.swing.JLabel memberIdTitle;
    private javax.swing.JLabel memberSearchTitle;
    private javax.swing.JTextArea memberTextArea;
    private javax.swing.JScrollPane memberTextScrollPane;
    private javax.swing.JRadioButton searchButton;
    // End of variables declaration                   
}

